server:
  port: 8083

spring:
  application:
    name: emi-service
  config:
    import: optional:configserver:http://localhost:8888

spring.cloud.openfeign.circuitbreaker.enabled: true

resilience4j:
  circuitbreaker:
    instances:
      notification-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
  timelimiter:
    instances:
      default:
        timeoutDuration: 5s
